config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # GET /TASKS
  get 'tasks', to: 'tasks#index', as: :tasks

  # GET /NEW and POST/NEW
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  # GET /TASK/:id
  get 'tasks/:id', to: 'tasks#show', as: :task

  # GET /NEW and POST/NEW
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # DELETE /restaurants/:id
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to '/tasks'
  end

  def edit
  end

  def update
    @task.update(task_params)
    # @task.update_column(completed: true) if params[:completed] == '1'

    redirect_to '/tasks', notice: 'task have been updated'
  end

  def destroy
    @task.destroy

    redirect_to '/tasks', notice: "#{@task.title} have been successfully destroyed"
  end
  
  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed, {}, true, false  %>

  <%= f.submit %>
<% end %>

<%= link_to "Back to list", "/tasks" %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
<div class="tasks">
<% if task.completed == true %>
<input type="checkbox" name=<%= task.title %> checked> <br> 
<% else %>
<input type="checkbox" name=<%= task.title %>> <br>
<% end %>
<%= link_to task.title, task_path(task) %>
<%= link_to destroy_path(task),  method: :delete, data: { confirm: 'Are you sure?' } do %>
  <%= image_tag('recycle_icon.png', alt:"delete", width:20, height:20) %>
<% end %>

</div>
<% end %>

<br>
<%= link_to 'Add a new task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

<%= link_to "Back to list", "/tasks" %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div><%= @task.details %></div>

<% if @task.completed == true %>
<input type="checkbox" name=<%= @task.title %> checked>This task is completed yet<br>
<% else %>
<input type="checkbox" name= <%= @task.title %> >This task is not completed yet<br>
<% end %>

<%= link_to "Back to list", "/tasks" %>

<p><%= link_to 'Edit this task', edit_task_path(@task) %></p>